### ISSUE TITLE
Can't save fund record changing from having restrictions to no restrictions

### ISSUE THREAD

**Issue by drkane** [TechforgoodCAST/beehive-giving#411]
Steps to replicate:

1. Load fund which has restrictions
2. Remove restrictions.
3. Press save - get validation error: `Restrictions can't be blank`
4. Untick "restrictions known"
5. Press save - get validation error: `Restrictions known can't be blank`

Something to do with interplay of these validations: https://github.com/TechforgoodCAST/beehive-giving/blob/master/app/models/fund.rb#L26-L27

**Comment by suninthesky** [comment]
Resolved with v3
